### ISSUE TITLE
Decide: disable scheduling on control planes?

### ISSUE THREAD

**Issue by athajaerel** [FatmanUK/k3s_amethyst#59]
No scheduling on control planes except for local-path, coredns and metrics server:
`kubectl taint node k3s-mother-0?.k3s.lab k3s-controlplane=true:NoSchedule`

Edit deployments/local-path-provisioner, deployments/coredns, deployments/metrics-server:
```
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
```
